//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "Accounts_Scheme", table_name = "Accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub account_id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub hash: String,
    pub salt: String,
    pub account_start_date: DateTime,
    pub account_deleted: bool,
    pub membership_status: bool,
    pub active_membership_start_date: Option<DateTime>,
    pub active_membership_end_date: Option<DateTime>,
    pub first_membership_date: Option<DateTime>,
    pub pro_status: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
